-- índices criados para conseguir buscas mais eficientes na tabela MV_DISTANCIAS (Ver em view/view.sql sua função)
CREATE INDEX IDX_MV_DISTANCIAS_ESTRELAS_ID1 ON MV_DISTANCIAS_ESTRELAS (ID_ESTRELA1);
CREATE INDEX IDX_MV_DISTANCIAS_ESTRELAS_ID2 ON MV_DISTANCIAS_ESTRELAS (ID_ESTRELA2);
